"""Load Google Earth Engine exports for the geoclimate-poa MVP."""

from pathlib import Path

import pandas as pd


def load_gee_table(input_path: str | Path) -> pd.DataFrame:
    """Load a tabular export generated by Google Earth Engine."""
    return pd.read_csv(input_path)


def validate_gee_columns(data: pd.DataFrame) -> pd.DataFrame:
    """Validate expected GEE export columns placeholder."""
    return data.copy()


def save_interim_table(data: pd.DataFrame, output_path: str | Path) -> None:
    """Save an interim table to Parquet."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data.to_parquet(output_path, index=False)


def main() -> None:
    """Run the GEE export loading workflow placeholder."""
    raise NotImplementedError("GEE export loading will be implemented in a future step.")


if __name__ == "__main__":
    main()

